### ISSUE TITLE
naming conflict if you have a dictionary with key == 'name'

### ISSUE THREAD

**Issue by skamsie** [brennv/namedtupled#10]
```
d = {'name': 'test'}
cat = namedtupled.map(d)
print(cat.name)

# TypeError: namedtuple_wrapper() got multiple values for argument 'name'
```

quick fix: rename first parameter in ```namedtuple_wrapper``` to ```_name``` which is less likely to be encountered as a key in a dictionary :)

**Comment by brennv** [comment]
Closed with #11 and #12. @skamsie thank for reporting this. @AndersonFirmino thanks for the PR. Pypi version bumped to 0.3.
